project_id = "qtduseiexmhssdkzjwbn"

[functions.send-recap-sms]
verify_jwt = false

[functions.send-rsvp-sms]
verify_jwt = false

[functions.send-checkin-sms]
verify_jwt = false

[functions.create-afterparty-checkout]
verify_jwt = false

[functions.verify-afterparty-payment]
verify_jwt = false
