project_id = "qtduseiexmhssdkzjwbn"

[functions.send-recap-sms]
verify_jwt = false

[functions.send-rsvp-sms]
verify_jwt = false

[functions.send-checkin-sms]
verify_jwt = false

[functions.create-afterparty-checkout]
verify_jwt = false

[functions.verify-afterparty-payment]
verify_jwt = false

[functions.create-lls-checkout]
verify_jwt = false

[functions.verify-lls-payment]
verify_jwt = false

[functions.admin-list-submissions]
verify_jwt = false

[functions.admin-update-submission]
verify_jwt = false

[functions.admin-list-events]
verify_jwt = false

[functions.admin-create-recap]
verify_jwt = false

[functions.artist-get-event]
verify_jwt = false

[functions.artist-update-event]
verify_jwt = false

[functions.artist-delete-message]
verify_jwt = false

[functions.artist-checkin-attendee]
verify_jwt = false

[functions.afterparty-upload-flyer]
verify_jwt = false
